### ISSUE TITLE
Documentation on wiring

### ISSUE THREAD

**Issue by IDmedia** [abrugsch/GBCartSlurp#4]
Love your project and I'm really happy I found it through Reddit.
I've been working on a similar solution for two month without getting it to work properly so I'm really looking forward trying yours. Do you have some better pictures of the circuit or schematic on how to wire those two expanders?

**Comment by abrugsch** [comment]
Yes, I'm working on getting the schematic done in KiCAD so a PCB can be made. this is happening now. Thanks for the interest! 👍

**Comment by abrugsch** [comment]
Added an SVG for wiring in commit 9e8aafe

Full Schematic and PCB layout to follow

**Comment by abrugsch** [comment]
full schematic added in commit b9ac58e
